name = "case-management-training"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./" 

[[d1_databases]]
binding = "DB" 
database_name = "lshcasemanagementtraining-trainingcrmlogins-v3"
database_id = "10414834-819b-47c4-8918-77f66a24b9e9"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "lshtraining"
