name: Vacuum D1 database

on:
  workflow_dispatch:

jobs:
  vacuum:
    runs-on: ubuntu-latest
    steps:
      - name: Run VACUUM on D1
        run: npx wrangler d1 execute lshcasemanagementtraining-trainingcrmlogins --remote --command "VACUUM;"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: a5bc4befef0191374735bd6a0109fec0
